### ISSUE TITLE
com.mongodb.ServerAddress

### ISSUE THREAD

**Issue by malpaso** [henrylearn2rock/MongoCFC#1]
Hi,

Any ideas on how to create com.mongodb.ServerAddress arrays?

/**
    @replicaSetSeeds Array of com.mongodb.ServerAddress
*/

**Comment by henrylearn2rock** [comment]
you can use CF array since it is just an ArrayList.

So, something like:

```
replicaSetSeeds = [
  createObject("java", "com.mongodb.ServerAddress").init("host", javacast("int", port))
];
```

see: http://api.mongodb.org/java/2.6/com/mongodb/ServerAddress.html

**Comment by malpaso** [comment]
Cheers Henry, I'll give it a go.
